# Note: this file's config overrides the Netlify UI admin config
# due to using a monorepo it can be a bit messy to configure Netlify
# See also https://github.com/netlify/build/issues/2483

[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.5"
  NODE_VERSION = "14"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["node_modules/.cache/babel-loader", "node_modules/.cache/terser-webpack-plugin"]
